### ISSUE TITLE
Question: Does it work just for the browser, how we should use it in node?

### ISSUE THREAD

**Issue by josoroma** [nobrainr/morphism#135]
Hi!

I was wondering... does it work just for the browser, how we should use/require it in node?

Thanks!

**Comment by emyann** [comment]
Hi @josoroma !

Thank you for considering using `Morphism`! You can absolutely use it in `Node` if you want. By using `require` or `import`. Please see a live example here: https://repl.it/@yrnd1/Morphism-CreateSchema

Do you encounter any issues doing this ?

**Comment by josoroma** [comment]
@emyann, thank you for the/your quick reply!

Yes I am, in an AWS Step Function:

![image](https://user-images.githubusercontent.com/69951/66168368-63c5c180-e5fa-11e9-836a-e693811354a7.png)

```
"use strict";

const morphism = require("morphism").Morphism;

module.exports.handler = async (event, context, callback) => {
  function HandleErrorOnSistem(message) {
    this.name = "HandleErrorOnSistem";
    this.message = message;
  }

  HandleErrorOnSistem.prototype = new Error();

  const source = {
    _firstName: "Mirza"
  };

  const schema = {
    name: "_firstName"
  };

  console.log("=====> HERE");

  const data = morphism(schema, source);

  console.log("=====> data", data);

  return {
    course: event.course
  };
};
```

or using:

```
const morphism = require("morphism")
```

**Comment by emyann** [comment]
My pleasure! :) 

Ah I see your issue, `Morphism` output an object that you can use if you want to use the internal registry to store your mappings https://github.com/nobrainr/morphism#Registry-API
```
const Morphism = require("morphism").default
Morphism(schema, data)
```

But the recommended approach if you don't use the registry is to destructure the `morphism` function
```
const { morphism } = require("morphism");
morphism(schema, data)
```

Here's is a working example: https://repl.it/@yrnd1/RuddyPessimisticBetatest

Please let me know if it works for you :)

**Comment by josoroma** [comment]
The recommended approach didn't work to me:

![image](https://user-images.githubusercontent.com/69951/66204377-f94b6a80-e667-11e9-85c5-7ba53a15bc71.png)

but:

```
const Morphism = require("morphism").default
Morphism(schema, data)|
```

Yes, it does. Thanks a bunch @emyann !
