### ISSUE TITLE
Mocking `morphism` named export

### ISSUE THREAD

**Issue by cjancsar** [nobrainr/morphism#137]
Can seem to mock the named export `morphism` in my tests.

```
import { morphism } from 'morphism'

morphism = jest.fn()
```

This throws '"morphism" is read-only'

I want to be able to spy on morphism, to make sure function is being called.

**Comment by cjancsar** [comment]
Resolved with:

```
jest.mock('morphism', () => ({
    morphism: jest.fn().mockImplementation(() => { ... mock implementation })
}))
```

**Comment by emyann** [comment]
Thank you for sharing this recipe!
