### ISSUE TITLE
Dealing with undefined source ?

### ISSUE THREAD

**Issue by iangregsondev** [nobrainr/morphism#162]
Hi, 

My destination argument passed to the schema, i can't be certain its an actual object, it could be undefined - it comes from a rest endpoint.

When i try to map it, it doesn't map anything. I am sure doing something wrong

```
  getUserProfileExistsSchema(): Schema<UserProfileExistsDto, Responses.UserProfileResponse|undefined> {
    const schema: Schema<UserProfileExistsDto, Responses.UserProfileResponse| undefined> = {
      value: source => source?.backgroundColor !== undefined && source?.phrase !== undefined,
      correlationId: () => this.correlationService.getCorrelationId()
    }

    return schema
  }
```

The above is my schema on a method - the "source" could be undefined, i am using the safe navigation operator (?) - this is not the issue as i tested it.. In fact i am using the safe navigation operator throughout my code-base now :-)

Notice I am passing a union type for the source "Responses.UserProfileResponse | undefined"

Then to map i do the following

```
morphism.map(this.userProfileResponseSchema.getUserProfileExistsSchema(), userProfile)
```

if i pass userProfile as undefined, I get an empty object back.

What is the correct way of support this kind of functionality?

Thanks in advance

**Comment by emyann** [comment]
Hello @iangregsondev! Can I know which version of `Morphism` you're actually using ? Per the example you shared, I guess the output you would expect is ?

```
{
  value: false,
  correlationId: 'some-correlation-id'
}
```

Are you using `morphism.map` function because you're using the registry to store your ES6 class types ?

**Comment by iangregsondev** [comment]
yes, exactly.

I am using the map function yes but I am not using a registry.

I am passing the schema as the first param and the source as the second.

Here is the version i am using

"version": "1.12.3"

**Comment by emyann** [comment]
Ok I see, thanks for the details. The thing is `Morphism` will always respect the `dimension` of the input, if it's undefined, it won't try to map it.

There's still a workaround if you wrap your object in an array, it means that the object to map is not undefined, but the values into it. Please see the example below: https://repl.it/@yrnd1/AdeptGranularFlashdrives

```typescript

import { createSchema, morphism } from 'morphism'

interface UserProfileResponse {
  backgroundColor: string,
  phrase: string
}
interface UserProfileExistsDto {
  value: boolean,
  correlationId: string
}


const schema = createSchema<UserProfileExistsDto, UserProfileResponse | undefined>({
  value: source => source?.backgroundColor !== undefined && source?.phrase !== undefined,
  correlationId: () => 'correlation-id'
})

const res = morphism(schema, [undefined])
console.log(res)
// => [ { value: false, correlationId: 'correlation-id' } ]
```
Let me know if it helps! This going to be better with the validation features coming in `Morphism v2`.

Also I recommend to use the `morphism` function instead of `morphism.map` if you don't use ES6 Class, since this is going to be refactored for `v2`

**Comment by iangregsondev** [comment]
Thanks you !
