### ISSUE TITLE
Unmap Mapped Object

### ISSUE THREAD

**Issue by sakthig** [nobrainr/morphism#18]
Is there a way to unamp i.e. Morphism Object -> JSON String based on the schema ?

**Comment by emyann** [comment]
Hello @sakthig 👋🏽

Actually this feature is not available but I think what you're looking for is a `reverseMap()` like, I plan to add it soon to handle this kind of scenario. 
You still can achieve this with Morphism by using 2 schemas, 1 regular for you incoming transformation, and 1 reversed for your outgoing transformation. 
Here is an example, please let me know if that answers to your question 🙂

https://repl.it/@yrnd1/Morphism-ReverseMap

```javascript
import morphism from 'morphism';
 
// Sample of data to transform to and from
const json = { 
    property: 'value'
}

// Morphism schema
const schema = { 
    field: 'property'
}

// Domain Object
class DomainObject {
    constructor(){
        this.field = null;
    }
}
morphism.register(DomainObject, schema)
const domainObject = morphism.map(DomainObject, json)
console.log(domainObject)
// => DomainObject { field: 'value' }

// ReverseMap Workaround
// Morphism reverse schema
const reverseSchema = { 
    property: 'field'
}
const reverseMap = morphism(reverseSchema)
let jsonObject = reverseMap(domainObject)
console.log(jsonObject)
// => { property: 'value' }

/** Or you could use a DTO like object to achieve the same result **/
// Structure matches json data
class ExternalObject {
  constructor(){
    this.property= null
  }
}
morphism.register(ExternalObject, reverseSchema)

const externalObject = morphism.map(ExternalObject, domainObject)
console.log(externalObject)
// => ExternalObject { property: 'value' }

```

**Comment by GregorBiswanger** [comment]
Hi there,
Is there already the possibility to use a reverse map without any additional effort?

Especially for REST APIs this is essential.. you have your db entities and want to convert them into DTOs.. and from DTO to db entities too..

Thank you and thank you for the great library
