### ISSUE TITLE
A merge method for copying properties with mappings

### ISSUE THREAD

**Issue by maca-sys** [nobrainr/morphism#190]
Hi, I'm sorry if this has been explained somewhere, but I could not find it. I am in desperate need of a merge method for copying all the properties to destination and for the ones that are present in the schema, the mappings are applied.

In summary:

Copy properties from the source object to destination object by following the mapping defined by map object and you can have all the source objects, even if no mapping has been defined.

For example:
```
const source = {
  _firstName: 'Mirza',
lastName:'Ta'
};

const schema = {
  name: '_firstName'
};
morphism.merge(schema, source);
➡
{
  "name": "Mirza",
lastName:'Ta'
}
```

**Comment by emyann** [comment]
@masoudtahmasebi93 Thank you for using `Morphism`! 

I think I understand what you're looking for. There is no merge function but you should be able to achieve it if you're using ES6 Class or by leveraging ES6 object spread. Does this comment help you in any way https://github.com/nobrainr/morphism/issues/185#issuecomment-594878699 ?

Please let me know, if this works for you, I'll likely add a section in the documentation for that.

Thanks!

**Comment by maca-sys** [comment]
Thank you so much @emyann.
Based on the comment, I wrote the following function and I think it can be a handy:
```
export const mergeWithMapping = (schema,source ) => {
    const partial = morphism(schema, source)
    const final = { ...source , ...partial }
    return final;
}
```
I'm using this function in my MappingService.js and it can be used wherever I need it.
Thank you so much. 
I thought this functionality was a must-have and when I didn't find it in the Docs, I was sure that I have not read it completely.

**Comment by emyann** [comment]
@masoudtahmasebi93 Nice !! Love it!

 I'll evaluate the possibility to have that baked in `Morphism`. It could be a mapping option on the schema (`eager` / `lazy` for  instance).

Thank you for the feedback and bringing that up 👍🏽

**Comment by maca-sys** [comment]
@emyann Let me know if there is anything I can help with, I will be more than happy. 
Thank you for your considerations.

**Comment by emyann** [comment]
@masoudtahmasebi93 Great! Thank you! I'm gonna think about the implementation, and I'll bring you to the conversation if you're interested.

I'm closing this issue for now. Thanks!
