### ISSUE TITLE
How to map nested types

### ISSUE THREAD

**Issue by jbeckton** [nobrainr/morphism#228]
Hello,

I have a scenario where I need to reuse a schema in another schema.

class Section {
  name: string;
  categories: Category[]; 
}

I have a schema for my Section class and one for my Category class but I was wondering how to use the Category schema with the Section schema?  I was thinking about using a function in my Section schema for the categories property that calls the Morphism currying function using my Category schema, sound correct?

Thanks

**Comment by emyann** [comment]
Hello @jbeckton, thank you for using `morphism`! Yes that's a good way to do it! I usually compose my transformers when I need to achieve what you're looking for. 

Below is an example

```ts
import {morphism, createSchema} from 'morphism'

const toCategory = morphism(createSchema<XXX, Category>({....}))

const toSection = morphism(
  createSchema<YYY, Section>({
    name: ({ name }) => name
    categories: ({ categories}) => toCategory(categories)
  })
)
```

**Comment by jbeckton** [comment]
That's what I will do then...

Thanks for the snippet, I never thought to use destructuring!

been using source object as input... `id: (source) => source._id?.toString()`

Kudos, I love the simplicity of Morphism. I think it's simplicity makes it more powerful. I am switching from an auto-mapper lib to Morphism for this very reason. Plus the auto-mapper started acting funny and over writing db values with nulls causing data loss, I can't have that.
