### ISSUE TITLE
Map multiple properties to an array

### ISSUE THREAD

**Issue by Yaty** [nobrainr/morphism#48]
Hey,

Let's say this is the input : 

```js
{
  a: {
    b: 'c',
    d: 'e',
  },
  f: {
    b: 'f',
    d: 'g',
  }
}
```

Is it possible to transform this into : 

```js
{
  k: [{
    b: 'c'
  }, {
    b: 'f'
  }]
}
```

I tried with this : 

```js
  const firstSchema = {
    b: 'b',
  };

  const secondSchema = {
    k: {
      path: ['a', 'f'],
      fn: (data) => morphism(firstSchema, data),
    },
  };
```

I get this : 

```js
{
 "k": {
    "b": "c"
  }
}
```

Thanks,

**Comment by emyann** [comment]
Hey @Yaty !

Thanks for using `Morphism`! 

You could achieve what you're looking for with the code below:

https://stackblitz.com/edit/typescript-tdav4y
```
// Source
const source = {
  a: {
    b: 'c',
    d: 'e',
  },
  f: {
    b: 'f',
    d: 'g',
  }
}

// Target
const target = {
  k: [{
    b: 'c'
  }, {
    b: 'f'
  }]
}

const firstSchema = {
  b: 'b'
}

const secondSchema = {
  k: item => morphism(firstSchema , Object.values(item))
};

// or

const secondSchema = {
    k: {
      path: ['a', 'f'],
      fn: item => morphism(firstSchema , Object.values(item))
    },
  };

const result = morphism(secondSchema, source)
```

You were close of the result, when you aggregate multiple properties using `path:['prop1', 'prop2']` or when you grab the whole input with `prop: (input)=>...` you'll always end up with an object of the aggregated fields (`{prop1:..., prop2:...}`). 
Morphism always respects the dimension of the input (e.g `morphism(schema, {}) => {}`, `morphism(schema, []) => []` ), so `Object.values` here allow to iterate on each part you want to transform.

Let me know if you need further explanation. We can update the Readme too if you find it would be helpful.

**Comment by Yaty** [comment]
Thank you ! I think it can be nice to have examples in a folder or in the Readme, to prevent people like me opening issues :rofl:

**Comment by emyann** [comment]
@Yaty Thank you for your feedback! This is a good idea, I will add an `examples` folder oriented on real case uses, it will add up to the more technical examples present in the readme.

Closing this 👍🏽

Thank you :)
