### ISSUE TITLE
Missing attributes during conversion using an ActionFunction with morphism()

### ISSUE THREAD

**Issue by terlar** [nobrainr/morphism#52]
If I have a definition such as:
```ts
interface Grade = {
  level: 'A'|'B'|'C'
  note?: string
}
interface Student = {
  name: string
  grade?: Grade
}

interface StudentDocument = {
  name: string,
  grade_data?: {
    level: 'A'|'B'|'C'
    note?: string
  }
}

const gradeSchema: StrictSchema<Grade> = {
  level: 'level',
  note: 'note'
}
const studentSchema: StrictSchema<Student, StudentDocument> = {
  name: 'name',
  grade: ({ grade_data }: any) => morphism(gradeSchema, grade_data),
}
```

Then the following function call will give:
```ts
morphism(studentSchema, { name: 'John Doe' })
{ name: 'John Doe',
  grade: [Function] }
```

I can wrap this in something like:
```ts
grade: ({ grade_data }: any) => grade_data ? morphism(gradeSchema, grade_data) : null
```

However it would be nice if the morphism never resulted in a function even with missing values. What is the strategy when working with optional values?

**Comment by emyann** [comment]
Hello @terlar,

Thank you for the feedback.

By design `Morphism` is a currying function emitting either the final result, or a mapping function aimed to be reused later.

_Without any source, keep the mapper to be reused later_
 ```
const mapper = morphism(schema)
// mapper(source) => final result
```
_Straight map when a schema and a source are provided_

```
const result = morphism(schema, source)
```

If you are not sure of the value of `grade_data` when you are doing some nested mapping you have the good approach with:
```
grade: ({ grade_data }: any) => grade_data ? morphism(gradeSchema, grade_data) : null
```
Also this brings the opportunity for you to normalize the data you want to expose. 

What would you expect as a return value if `morphism(gradeSchema, grade_data)` didn't fallback on the mapper function ?

**Comment by terlar** [comment]
I think if the type declaration is optional it should act as if the value was not provided and omit the key completely, e.g.:

```
> interface MyTest {
... aProperty: string
... bProperty?: string
... }
undefined
> let a: MyTest = { aProperty: 'hello' }
undefined
> a
{ aProperty: 'hello' }
```

However it would be nice if you could enforce the types if they are not optional, e.g.:
```
> let a: MyTest = { }
[eval].ts(5,5): error TS2322: Type '{}' is not assignable to type 'MyTest'.
  Property 'aProperty' is missing in type '{}'.

undefined
```

In the cases of non-optional types I do agree that there is not default fallback and should probably error out instead, or force the transformation to specify how to handle that.

The problem with the functions although i understand from an implementation behavior how that is neat. But in the final transformation if you did some mistake or whatever, a function is never the correct value? At least not when working with plain data.

**Comment by emyann** [comment]
> I think if the type declaration is optional it should act as if the value was not provided and omit the key completely

> The problem with the functions although i understand from an implementation behavior how that is neat.

Yes I do agree with this one. I won't be able to know at runtime if the field is optional from TypeScript , but I can definitely omit the key if the transformation returns an undefined value. I will create a PR for that 👍 

> However it would be nice if you could enforce the types if they are not optionalHowever it would be nice if you could enforce the types if they are not optional

Do you use the last version of `Morphism` ? Some improvements has been made on TypeScript types to help this kind of scenario. In [v2](https://github.com/nobrainr/morphism/issues/47) I am planning to let the user opt in for runtime warning when a schema is not met (e.g: a transformation returning an undefined value)

**Comment by terlar** [comment]
I installed it via NPM this weekend, so it should have been the latest published at that point. I saw your road-map and it looks promising. Looking forward to use this more, all really good ideas. I think this has the best TypeScript integration what I have seen. I have been running into things complaining due to missmatching types which is good. Perhaps add the possibility to apply some transformation on the final result. I know I can do it on the result from `morphism`, but when you are working with arrays it would be nice to apply such a function to all entries without manually using map. My only current use case though is to be able to strip undefined keys (that was optional).

**Comment by emyann** [comment]
Thank you so much for the kind words and the feedback 🙏🏽 

> Perhaps add the possibility to apply some transformation on the final result. I know I can do it on the result from `morphism`, but when you are working with arrays it would be nice to apply such a function to all entries without manually using map

I am not sure I understood this correctly but you actually have the ability to use Morphism on Objects and Arrays, the rule is it will always respect the input dimension:

e.g.

```
morphism(schema,{}) => {} // Apply the transformation on the input object

morphism(schema, [{},{}]) => [{},{}] // Apply the transformation on the input array
```

I will work on stripping the undefined keys starting next week I think, thank you for the suggestion! :)

**Comment by terlar** [comment]
You are welcome.

Yes, you understood me partly, sorry for being a bit unclear. I see now that it was just a blob of text and not very structured.

That is what I meant, since it supports both arrays and direct objects. If you want to apply some function to the transformation you have to be aware of the result being worked on is an array or not and if it is an array you have to manually map as shown. My thought was what the procedure was if you always wanted some post-processing of your morphism transformation, per object level.

I am not sure there is a strong use case, but such as thing as removing null values, etc. could be a thing for the post processing step.

**Comment by emyann** [comment]
@terlar I made a little fix to avoid a function instead of a undefined property in the case of mapping a undefined data source https://repl.it/@yrnd1/Morphism-undefined-data-source This fix is available with [version 1.9.2](https://github.com/nobrainr/morphism/releases/tag/v1.9.2)

I will add some options along the schema in order to apply some strategies on null and/or undefined values. I will think about your suggestion on some processing steps  as well as.

**Comment by terlar** [comment]
@emyann Nice! Thanks, this made me be able to replace a pattern where I had a `morphismOrNull` function that wrapped this, returning null if there was no value otherwise apply the morphism function. Only difference is that I returned `null` instead of `undefined`.

In this case I would still prefer to have the key omitted, but I guess I could have some manual post-processing. So would appreciate some options like that, let me know and I will test it :)

**Comment by emyann** [comment]
@terlar Thank you for your feedback ! I did release a new version [1.10](https://github.com/nobrainr/morphism/releases/tag/v1.10.0) with which it is possible to either **strip the key when the value is undefined** or provide a **default value to replace undefined one**s.

To do so it is now possible to create a schema with options using the `createSchema` function.

### Strip undefined value
```typescript 
import { createSchema, morphism } from 'morphism'

const schema = createSchema<Target>({ keyA: 'somepath' }, { undefinedValues: { strip: true } })
// => {}
```

### Default value fallback
```typescript 
import { createSchema, morphism } from 'morphism'

const schema = createSchema(
  { keyA: 'somepath' },
  {
    undefinedValues: {
      strip: true,
      default: () => null
    }
  }
);
// => { keyA: null }
```


Here's a playground if you want to see it working: https://repl.it/@yrnd1/Morphism-undefined-values

Please let me know what you think about it and don't hesitate if you have questions :)

**Comment by terlar** [comment]
Sorry for the delay, I didn't have time to update my implementation to use this until now. Just want to return here to say thank you and I am very satisfied with the current behavior. Keep up the good work :+1:

**Comment by emyann** [comment]
I really appreciate your feedback @terlar! Thank you and let me know if you need further support :)
