### ISSUE TITLE
[TS] Issue on example with Array

### ISSUE THREAD

**Issue by Sangrene** [nobrainr/morphism#69]
I just copied this example :
```
// What we have
interface Source {
  ugly_field: string;
}

// What we want
interface Destination {
  field: string;
}

const source: Source = {
  ugly_field: 'field value'
};

// Destination and Source types are optional
morphism<Destination, Source>({ field: 'ugly_field' }, source);
// => {field: "field value"}

// Or
const sources = [source];
const schema: StrictSchema<Destination, Source> = { field: 'ugly_field' };
morphism<Destination, Source>(schema, sources);
// => [{field: "field value"}]
```
And I got the following error when applying morphism which is suppose to return an array : 
```
Argument of type 'StrictSchema<Destination, Source>' is not assignable to parameter of type 'Destination'.
  Types of property 'field' are incompatible.
    Type 'string | string[] | ActionFunction<Destination, Source, string> | "ugly_field"[] | ActionSelector<Source, string>' is not assignable to type 'string'.
      Type 'string[]' is not assignable to type 'string'.ts(2345)
```

Any tips on how to solve this problem ?

**Comment by emyann** [comment]
Hello @Sangrene !

Thanks for using `Morphism`. It seems to be a documentation issue: instead of `morphism<Destination, Source>(schema, sources);` you could just remove the typing `morphism(schema, sources);` 

As long as your schema is typed, the type of the destination will be inferred from the schema and the input (object or array).
 
<img width="684" alt="Screen Shot 2019-05-10 at 7 47 17 AM" src="https://user-images.githubusercontent.com/4748419/57525216-20d81a00-72f8-11e9-98c4-c88a1d7c286a.png">

Thanks for the feedback and sorry about that, I'll update the documentation on this point. Here's a working repl of this example: https://repl.it/repls/FearfulDisloyalCompiler.

Let me know if you have further questions!

**Comment by Sangrene** [comment]
Hi @emyann, 

Thanks for answering that fast, however I still have a problem :

Why does this code works : 
```
// What we have
interface Source {
  ID: string;
}

// What we want
interface Destination {
  id: string;
}

const rows: Array<Source> = [];


const schema: StrictSchema<Destination, Source> = { id: 'ID' };
console.log(morphism(schema, rows))
console.log(morphism(schema, rows)[0].id)

```

But this code doesn't : 
```
// What we have
interface Source {
  ID: number;
}

// What we want
interface Destination {
  id: number;
}

const rows: Array<Source> = [];


const schema: StrictSchema<Destination, Source> = { id: 'ID' };
console.log(morphism(schema, rows))
console.log(morphism(schema, rows)[0].id)
```
The error is on the last line : 
```
Argument of type 'Source[]' is not assignable to parameter of type 'Source'.
  Property 'ID' is missing in type 'Source[]' but required in type 'Source'.ts(2345)
```

**Comment by emyann** [comment]
Hmmfrr there is clearly a TypeScript issue with the inferred type when the input is an array 😬

As a workaround you could map on your input and morph each item: 
``` 
rows.map(morphism(schema))[0].id
``` 
<img width="680" alt="Screen Shot 2019-05-10 at 9 45 38 AM" src="https://user-images.githubusercontent.com/4748419/57532006-c98e7580-7308-11e9-85a2-85a34e86e258.png">

I am opening an issue for this and will work on it ASAP!

**Comment by Sangrene** [comment]
I knew there was something wrong with TS ! 
My typescript version is `3.1.3`, I will try with the latest version on Monday and keep you updated.

Workaround is working as expected, great lib and great support :)

**Comment by emyann** [comment]
@Sangrene And you were right. Good catch on this one! 😀 

Thank you for the kind words, I'll get you updated as soon as I worked on this issue 👌🏽 

Have a good weekend :)

**Comment by emyann** [comment]
@Sangrene The latest release: [`v1.10.2`](https://github.com/nobrainr/morphism/releases/tag/v1.10.2) should fix the TypeScript issue. Here's a working version of your example above https://repl.it/@yrnd1/LumberingStupidTheories

Please let me know when you've updated the version if everything is alright then I'll proceed to close this issue.

Again, thanks a lot for the feedback! 🙏🏽

**Comment by Sangrene** [comment]
Everything is alright with latest release 1.11.0 !
Closing this issue :)
