### ISSUE TITLE
Typescript StrictSchema<Destination, Source> output {Object} instead of Destination

### ISSUE THREAD

**Issue by m4ss1m0g** [nobrainr/morphism#76]
``` typescript
// What we have
class Source {
    public id!: number;
    public ugly_field!: string;
}

// What we want
class Destination {
    public id?: number;
    public field!: string;
}

const source: Source = {
    id: 1,
    ugly_field: "field value",
};

const schema = { field: "ugly_field" };

const result = morphism<StrictSchema<Destination, Source>>(schema, source);
const h = result.constructor.name;

console.log(h);
```

Output

> Object
> {"field":"field value"}

To obtain the Destination object must use the _plain_ schema and use Destination has last parameter on _morphism_

``` typescript
const result = morphism(schema, source, Destination);
```

Output
>Destination
>{"field":"field value"}

**Comment by emyann** [comment]
@m4ss1m0g When using the morphism `function` instead of the `registry` this is how you output ES6 Class Objects
``` 
const result = morphism(schema, source, Class)
// => result is typeof Class
```

**Comment by m4ss1m0g** [comment]
Yes Ii know, but I cannot use `StrictSchema `and the `morphism `function using the destination class.

``` typescript
import Morphism, { morphism, StrictSchema } from "morphism";

// What we have
class Source {
    public id!: number;
    public ugly_field!: string;
}

// What we want
class Destination {
    public id!: number;
    public field!: string;
}

const source: Source = {
    id: 1,
    ugly_field: "field value",
};

const schema = { field: "ugly_field", id: () => 0 };
const a: StrictSchema<Destination, Source> = schema;
const result = morphism(a, source, Destination);

```

This code raise error on Typescript

> Argument of type 'StrictSchema<Destination, Source>' is not assignable to parameter of type 'Schema<any, any>'.
>   Property 'id' is incompatible with index signature.
>     Type 'string | number | string[] | ActionFunction<Destination, Source, number> | ("ugly_field" | "id")[] | ActionSelector<Source, number>' is not assignable to type 'string | string[] | Schema<any, any> | ActionFunction<any, any, any> | (string | number | symbol)[] | ActionSelector<any, any> | undefined'.
>       Type 'number' is not assignable to type 'string | string[] | Schema<any, any> | ActionFunction<any, any, any> | (string | number | symbol)[] | ActionSelector<any, any> | undefined'.


Anyway if I force compilation on .js I obtain this code

``` typescript
const schema = { field: "ugly_field" };
const a = schema;
const result = morphism_1.morphism(a, source, Destination);

```
That it correctly returns the target class, can be the error in the typescript declaration file?

**Comment by emyann** [comment]
@m4ss1m0g Please can you let me know which version of `Morphism` do you actually use ? Here's a repl with the latest version `v1.12.0` where you can use a StrictSchema while being able to output a class object https://repl.it/@yrnd1/LastSmartMultitasking

<img width="495" alt="Screen Shot 2019-05-27 at 8 09 44 PM" src="https://user-images.githubusercontent.com/4748419/58434379-ac54f780-80bb-11e9-8c18-99b3e9462c1a.png">
<img width="304" alt="Screen Shot 2019-05-27 at 8 09 49 PM" src="https://user-images.githubusercontent.com/4748419/58434391-b4ad3280-80bb-11e9-8878-9bb3c7c8d5f8.png">


There are 2 examples in the repl, one using the `createSchema` helper and the option to turn off the automapping, and another without the helper. 

Please let me know if you need further explanation, or if I can close this issue :)

Thanks!

**Comment by m4ss1m0g** [comment]
I used the 1.10 version. 
Updating to the latest version 1.12.0 solve the issue.

Thanks.
